@extends('emails.layouts.master')

@section('content')
    <h1 style="margin-bottom: 8px;">{{ $subject ?? 'System Notification' }}</h1>
    
    @if(isset($name))
        <p style="font-size: 16px; color: #475569; margin-bottom: 24px;">Hello {{ $name }},</p>
    @endif

    <div class="callout" style="border-left: 4px solid #0ea5e9; border-radius: 8px;">
        <p style="margin: 0; white-space: pre-wrap; font-size: 15px; color: #334155;">{!! nl2br(e($messageText ?? 'A new alert has been generated by the system. Please log in to review any necessary actions.')) !!}</p>
    </div>

    @if(isset($actionUrl) && !empty($actionUrl))
        <div style="margin: 32px 0;">
            <a href="{{ $actionUrl }}" class="button button-primary" target="_blank">View Details</a>
        </div>
    @endif
@endsection
