@extends('emails.layouts.master')

@section('content')
    <h1 class="text-center">{{ $subject ?? 'System Notification' }}</h1>
    
    @if(isset($name))
        <p>Hello {{ $name }},</p>
    @endif

    <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 24px;">
        <p style="margin: 0; white-space: pre-wrap;">{!! nl2br(e($messageText ?? 'A new alert has been generated by the system. Please log in to review any necessary actions.')) !!}</p>
    </div>

    @if(isset($actionUrl) && !empty($actionUrl))
        <div class="text-center">
            <a href="{{ $actionUrl }}" class="button" target="_blank">View Details</a>
        </div>
    @endif

    <div class="divider"></div>
    <p class="text-sm text-muted">You are receiving this notification because it corresponds to activity monitored within your account on the Baakh platform.</p>
@endsection
